### ISSUE TITLE
Fobidden error

### ISSUE THREAD

**Issue by apryiomka** [microsoftgraph/aspnet-webhooks-rest-sample#5]
I cannot get this to work. I have a registered app at azure portal as well as I granted ALL permissions, but I receive forbidden message:
![untitled](https://cloud.githubusercontent.com/assets/11861671/19788873/054cac5e-9c60-11e6-8d43-2090bd39518b.png)

**Comment by DianeD** [comment]
Hi @apryiomka . I tried to reproduce your issue with a fresh install and registration, but it's working for me. 
![image](https://cloud.githubusercontent.com/assets/8431452/19824335/4e4c072e-9d23-11e6-8894-2e432fef36f1.png)
So mine is using just AAD "Sign in and read user profile" and Microsoft Graph "Mail.Read" for an Office 365 work account.

**Comment by cveld** [comment]
I had the same issue :(     For simplicity's sake I just signed out from the demo app, removed the app registration from AAD, and added it again. New client id and client secret. This time I generated the secret _after_ I had assigned the required additional permission. 

I think the issue was that I gave consent early on on a limited permission set. Afterwards I added the permission, but did not refresh any token. Ideally I would like to learn how I can enforce the refreshing when we will be adding permissions during the lifecycle of the app.

**Comment by DianeD** [comment]
Hi @cveld . Thanks for reporting this. Do you get the error when retrieving a changed email message? Are you getting error code "Authorization_RequestDenied" and message "Insufficient privileges to complete the operation."?

**Comment by cveld** [comment]
No I got the forbidden error when subscribing to the webhook. Sorry that I did not capture the full error json. Maybe I will register a new app without the required Mail.Read permission and enforce the error again.

**Comment by DianeD** [comment]
@cveld , I think I misread your first message. Did you resolve your Forbidden error by re-registering/regenerating the secret?

Regarding your question about adding permissions, that's supported with the [Azure AD v2.0 endpoint](https://azure.microsoft.com/en-us/documentation/articles/active-directory-appmodel-v2-overview). You can see how the flow works in the [ASP.NET snippets sample](https://github.com/microsoftgraph/aspnet-snippets-sample), though that sample uses the MSAL auth library instead of ADAL. And [this Azure AD sample](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2) describes the flow in detail in the “Handling incremental consent…” section.

**Comment by cveld** [comment]
We tried to resolve with only regenerating the secret. But this was not
enough. In the end we just registered a new app to get it work. Maybe we
just had to drop the user's consent first to resolve it more gracefully.

2016-11-15 19:24 GMT+01:00 DianeD notifications@github.com:

**Comment by DianeD** [comment]
Thanks again for the feedback! Added this use case to the Troubleshooting section of the readme. Closing this issue. @apryiomka , please reopen if this doesn't resolve your issue.
